move install dir from `~/Programs/KotlinCompiler` -> `~/Programs/Kotlin`, update to install Kotlin Native too

diff --git a/scripts/jvm-default/install b/scripts/jvm-default/install
--- a/scripts/jvm-default/install
+++ b/scripts/jvm-default/install
@@ -127,18 +127,18 @@ installJBR >> "$logOut" 2>&1
 function installKotlinCompiler() {
 	local needsSetup
 	needsSetup=0
-	if [ -d "./KotlinCompiler" ]; then
-		if [ -d "$(readlink -f "./KotlinCompiler/kotlin-compiler-latest")" ]; then
+	if [ -d "./Kotlin" ]; then
+		if [ -d "$(readlink -f "./Kotlin/kotlin-compiler-latest")" ]; then
 			true
 		else
 			needsSetup=1
 		fi
 		true
 	else
-		mkdir "./KotlinCompiler"
+		mkdir "./Kotlin"
 		needsSetup=1
 	fi
-	cd "./KotlinCompiler" || exit
+	cd "./Kotlin" || exit
 
 	local baseFile
 	baseFile="kotlin-compiler-$kotlinVersion"
@@ -189,5 +189,65 @@ function installKotlinCompiler() {
 installKotlinCompiler >> "$logOut" 2>&1
 
 function installKotlinNative() {
-	true
+	local needsSetup
+	needsSetup=0
+	if [ -d "./Kotlin" ]; then
+		if [ -d "$(readlink -f "./Kotlin/kotlin-native-latest")" ]; then
+			true
+		else
+			needsSetup=1
+		fi
+		true
+	else
+		mkdir "./Kotlin"
+		needsSetup=1
+	fi
+	cd "./Kotlin" || exit
+
+	local baseFile
+	baseFile="kotlin-native-prebuilt-linux-$(uname -m)-$kotlinVersion"
+	local tarFile
+	tarFile="$baseFile.tar.gz"
+	local baseURL
+	baseURL=https://github.com/JetBrains/kotlin/releases/download/v$kotlinVersion/$tarFile
+
+	wget "$baseURL"
+	wget "$baseURL.sha256"
+	echo " $baseFile" >> "$tarFile.sha256"
+
+	# Can't use 'shasum -a 256' since it's only available as sha512sum on Termux
+	sha256sum -c "$tarFile.sha256"
+
+	local sumStatus
+	sumStatus=$?
+
+	if [ $sumStatus -eq 1 ]; then
+		{
+			echo -e "Verification of Kotlin Native $kotlinVersion failed!\n"
+			cat "$tarFile.sha256"
+			echo -e "\n"
+			sha256sum "$tarFile"
+		} >> "$logOut"
+		rm "$tarFile"
+		rm "$tarFile.sha256"
+		exit
+	fi
+
+	mkdir "$tarFile"
+	tar -xzvf "$tarFile"
+
+	local symLinkInstall
+	symLinkInstall="$(realpath "kotlin-native-latest")"
+	ln -sf "$(realpath "$baseFile")" "$symLinkInstall"
+
+	if [ $needsSetup -eq 1 ]; then
+		fixMyJavaInstall "$symLinkInstall"
+	fi
+
+	rm "$tarFile"
+	rm "$tarFile.sha256"
+
+	cd ..
 }
+
+installKotlinNative >> "$logOut" 2>&1
